### ISSUE TITLE
Define Protocol Job Config

### ISSUE THREAD

**Issue by Poofjunior** [AllenNeuralDynamics/brainwasher#18]
## Requirements:

* protocol
  * a local copy of the protocol
  * a path to where the protocol originated from if it came from a csv or another job file.
    * file metadata information about when file at path was last changed.
* current pause/resume state
* record of:
  * start, restart, pause, resume, abort, completion history.
  * starting solution (what the reaction vessel started with when the brain was added)
* sample (or job name)

Let's imagine this job file as a high-level record of what was done to the sample without needing to go through the gory details of the logs.

Jobs should also be usable across machines. i.e: you could pause a job on one machine and resume it on another by transporting the sample and copying over the job file.

## Interface:
* The user will create a job file and then run it. Job files are autogenerated from protocols
  * `create_job(name, source)`
  * `run_job(job)`
* The user can only resume a job file
* The brainwasher software will work off of a job object instance.

Additionally, we should support:

* Multiple calls to pause/resume
* Restart
* Force-Restarting (discards history)
* Copy??

## Implementation
* We'll probably want something that lets us read/edit object attributes, but can serialize the contents to disk as a file for human readability. Pydantic would be a good choice for this.

**Comment by Poofjunior** [comment]
Here's a sketch of what this could look like:
```yaml
name: "my_job"
source_protocol:
  path: "/home/brainwasher/protocols/demo_protocol.csv"  # could be a path or url to a csv or another protocol.
  accessed: null

start_timestamp:
  null
end_timestamp:
  null

chemicals:
  - thf
  - dcm
  - pbs

resume_state:
  step: 1
  duration_s: 1800  # Overrides the current duration in that step
  start_empty: false

protocol:
  - run_wash_step:
      mix_speed_rpm: 1000
      duration_s: 3600
      solution:
        thf: 2500
        di_water: 7500
  - run_wash_step:
      mix_speed_rpm: 1000
      duration_s: 3600
      solution:
        thf: 5000
        di_water: 5000
  - run_wash_step:
      mix_speed_rpm: 1000
      duration_s: 3600
      solution:
        thf: 7500
        di_water: 2500
      end_empty: false

history:
  starting_solution:
    pbs: 10000
  execution_history:
    null
```
